### ISSUE TITLE
Request for Compatibility of Windows Operating System 

### ISSUE THREAD

**Issue by imeMFK01** [maltesie/bridge2#4]
Dear @maltesie,

Is it possible for you to add **windows compatibility** as well and if its already done then it would be great if you can update the installation guide?

Thanks.

**Comment by maltesie** [comment]
Hi,
I do not have access to a Windows machine and thus never tried to run bridge2 on Windows. In theory it should work, Qt and python being available on Windows. I will try to set up a virtual machine and see if I can write a shell script that sets up the virtual environment and starts bridge.
Best,
Malte

**Comment by imeMFK01** [comment]
Much appreciated for your timely response.
Sure that would be great and really helpful for those who are just working on Windows platform.
Looking forward to hear a good news from your side.

Regards,
Farhan

**Comment by maltesie** [comment]
Hi Farhan,
sorry for the delay, setting up Qt seems to be a bit more involved under Windows. I don't have much time to look into this, but I'm working on it. Just wanted to let you know.
Best,
Malte

**Comment by maltesie** [comment]
I'm also looking into deploying bridge2 as a conda package, I guess this should be the easiest way to install it on all platforms. But again, bundling everything with Qt seems to be a bit more involved. I will post updates here, once I made progress.

**Comment by maltesie** [comment]
I added an install and run .bat script and tested it under Windows 10.
