### ISSUE TITLE
Unable to view large trajectory file 

### ISSUE THREAD

**Issue by imeMFK01** [maltesie/bridge2#6]
Dear @maltesie

We are unable to view large trajectory file (15.1 GB) so would you please look into this also please find below system's information and attached error details (Error.JPG)

Operating System: Windows Server 2019
RAM: 256 GB

Moreover, if you have any query then please feel free to ask.

Thanks.

![Error](https://github.com/maltesie/bridge2/assets/45854202/b19cf038-7c16-4dc4-8e6b-4c6edfeaabac)

**Comment by maltesie** [comment]
Hi @imeMFK01 

I have never encountered this error before. It looks like the DCD reader has a problem with your file. Bridge uses the MDAnalysis package to read trajectories. I found this issue in their github:

https://github.com/MDAnalysis/mdanalysis/issues/3075

It seems it is specific to Windows and large DCD files. There is a workaround described there, maybe that can help you.

**Comment by imeMFK01** [comment]
Dear @maltesie,

Really thanks for this.
