### ISSUE TITLE
Bridge2 is not responding

### ISSUE THREAD

**Issue by imeMFK01** [maltesie/bridge2#7]
Dear @maltesie,

We are importing a trajectory file (15.1GB) having 20ns data which contains 40000 frames so while doing this we are facing three different scenarios (mentioned below) and all are ended up with **"Bridge2 is not responding"**. Moreover, CPU usage is going to 100% utilization but usage of RAM is only 17% (at max.).

1. <40000/40000 frames are processed 
2. 40000/40000 frames are processed 
3. all frames are processed 

**System Specifications**
Operating System:  Ubuntu 21.04
Processor: Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz -- 64bit
Total RAM Size: 32GB

Your help will be highly appreciable.

Thanks.

**Comment by imeMFK01** [comment]
Dear @maltesie,

Can you please look into this?

Thanks.

**Comment by maltesie** [comment]
Hi @imeMFK01 ,

I don't fully understand your situation. You start the analysis and then bridge gets stuck. And it is not reproducible where it gets stuck? Are you using the latest binaries? What does the status bar down to the left say when bridge is not responding?

Maybe a screenshot of the frozen window could help...

**Comment by GregorySchwing** [comment]
I have a similar issue.  I am trying to generate a H-bond network of a box of water (n=826), with a trajectory of 10 frames.

Here is a snapshot with the status bar.
![image](https://github.com/maltesie/bridge2/assets/39970712/a1e46804-7766-4d99-b0bf-84f872c994d4)

Here is how I am setting up the analysis
![image](https://github.com/maltesie/bridge2/assets/39970712/b118eeb6-5688-4bfd-b771-b03761680aa8)

Here are the files
[example.zip](https://github.com/maltesie/bridge2/files/12073507/example.zip)

**Comment by maltesie** [comment]
Hi @GregorySchwing 

the static selection should not contain water. Bridge detects water based on the water definition in the Settings and computes bonds between the static selection and water only for the 2. and 3. algorithm in the list.

**Comment by GregorySchwing** [comment]
> Hi @GregorySchwing
> 
> the static selection should not contain water. Bridge detects water based on the water definition in the Settings and computes bonds between the static selection and water only for the 2. and 3. algorithm in the list.

So, is it possible to use bridge to calculate the h-bonds in a box of water?

**Comment by maltesie** [comment]
You can do that, but bridge is designed as a graphical analysis tool and will always plot all resids involved in h-bonding. Computing the h-bonds works fine, but plotting 2500 water molecules and all the h-bonds between them is probably taking ages.

**Comment by maltesie** [comment]
It took a bit, but then I got:

![image](https://github.com/maltesie/bridge2/assets/8149211/46508f32-6e47-4140-8ede-a9b8c1e72ebf)

**Comment by GregorySchwing** [comment]
> It took a bit, but then I got:
> 
> ![image](https://user-images.githubusercontent.com/8149211/255840899-46508f32-6e47-4140-8ede-a9b8c1e72ebf.png)

Ok, I understand.  The long wait time is from the graphical plotting function.  Is there any way to skip graphical plotting and export to an edge list text file?  If not, I may fork bridges2 and add this functionality.

**Comment by maltesie** [comment]
Currently its not possible to turn off plotting. You are welcome to add this functionality, but I did not comment the code and there is no documentation...

**Comment by mahaamhamid** [comment]
@maltesie I understand that plotting of the protein water hydrogen bonds takes long time specially when analyzing larger trajectory. Is there any way once can cater this problem? I want to analyze a 10 ns trajectory, but it is talking ages to load.

**Comment by maltesie** [comment]
If you do not explicitly compute all protein-water interactions using the waterwire algorithm, the network only contains protein residues and will be drawn quickly. Or are you interested in having all  interactions explicitly? Generally this also leads to memory issues since there will be a lot of unique interactions only present for a few frames.

**Comment by mahaamhamid** [comment]
@maltesie I am interested in having all interactions. I am not very interested in plotting those interactions but rather in the occupancy value of the H-bond.

**Comment by maltesie** [comment]
This is not possible right now, I'm sorry. Maybe I can manage to implement this at some point, but I'm too busy right now.
