### ISSUE TITLE
cant get working for a host-guest system

### ISSUE THREAD

**Issue by GregorySchwing** [maltesie/bridge2#8]
[nonprotein.zip](https://github.com/maltesie/bridge2/files/11579364/nonprotein.zip)

I'd like to use bridge2, but I can't get this system to work.  I'd like to calculate Hbond interactions of waters within 3 ang of the host-guest sytem.  Unfortunately, no donors are found in the selection (resname MOL or resname OCT or resname WAT)

![image](https://github.com/maltesie/bridge2/assets/39970712/9b8c5849-2369-4428-aff2-5c72fe7cb5bd)

I can't even get it to just find Hbonds between waters with selection (resname WAT)

![image](https://github.com/maltesie/bridge2/assets/39970712/83cf6ca5-f387-4473-84d2-a021aa1c31d6)

Could you post an example or help me with this one?

Sincerely

Gregory Schwing

**Comment by maltesie** [comment]
Hi,

bridge needs you to define the donor and acceptor atoms as well as the water oxygen atoms in the settings menu under edit -> settings. If that is set for your system, you can supply a selection of your molecule in the "New analysis" dialog. In your case that would be "resname OCT or resname MOL" (I think) and then select the "H-bonds in static selection and water around ..." algorithm. With these settings I get the following: 
![image](https://github.com/maltesie/bridge2/assets/8149211/ed4ae6d4-7689-4dbc-94ab-c2f70b44b62d)
