### ISSUE TITLE
Input PDB file

### ISSUE THREAD

**Issue by mahaamhamid** [maltesie/bridge2#9]
I have simulated a protein using gromacs. Bridge2 successfully read the .xtc file but it does not read the the .gro file for the coordinates. I tried to convert the gro file to pdb file using editconf but it still gives an error. Most specifically I think it cannot identify the local water index in the converted pdb file. Is there any solution to how I can tackle this error? 
![image](https://github.com/maltesie/bridge2/assets/47174635/2a52fbd9-8bbf-47d4-914d-c1c70e8780cd)

**Comment by maltesie** [comment]
It looks like there are no water detected in your file. Which refname and segname do your water molecules have? Under Settings, you can find a dialog where you can change the definition of water molecules. Does that help?

**Comment by mahaamhamid** [comment]
Thank you so much. My input file has SOL as residue name that's why the software was unable to recognize it.
